import { KeyKind } from "./kinds";

export const KeyConfig: KeyConfigType[][] = [
    [
        {symbol: "", kind: KeyKind.STANDARD, code: "Escape"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Digit1"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Digit2"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Digit3"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Digit4"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Digit5"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Digit6"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Digit7"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Digit8"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Digit9"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Digit0"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Minus"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Equal"},
        {symbol: "", kind: KeyKind.BIG, code: "Backspace"},
    ],
    [
        {symbol: "", kind: KeyKind.LARGE, code: "Tab"},
        {symbol: "Q", kind: KeyKind.STANDARD, code: "KeyQ"},
        {symbol: "W", kind: KeyKind.STANDARD, code: "KeyW"},
        {symbol: "E", kind: KeyKind.STANDARD, code: "KeyE"},
        {symbol: "R", kind: KeyKind.STANDARD, code: "KeyR"},
        {symbol: "T", kind: KeyKind.STANDARD, code: "KeyT"},
        {symbol: "Y", kind: KeyKind.STANDARD, code: "KeyY"},
        {symbol: "U", kind: KeyKind.STANDARD, code: "KeyU"},
        {symbol: "I", kind: KeyKind.STANDARD, code: "KeyI"},
        {symbol: "O", kind: KeyKind.STANDARD, code: "KeyO"},
        {symbol: "P", kind: KeyKind.STANDARD, code: "KeyP"},
        {symbol: "", kind: KeyKind.STANDARD, code: "BracketLeft"},
        {symbol: "", kind: KeyKind.STANDARD, code: "BracketRight"},
        {symbol: "", kind: KeyKind.LARGE, code: "Backslash"},
    ],
    [
        {symbol: "", kind: KeyKind.BIG, code: "CapsLock"},
        {symbol: "A", kind: KeyKind.STANDARD, code: "KeyA"},
        {symbol: "S", kind: KeyKind.STANDARD, code: "KeyS"},
        {symbol: "D", kind: KeyKind.STANDARD, code: "KeyD"},
        {symbol: "F", kind: KeyKind.STANDARD, code: "KeyF"},
        {symbol: "G", kind: KeyKind.STANDARD, code: "KeyG"},
        {symbol: "H", kind: KeyKind.STANDARD, code: "KeyH"},
        {symbol: "J", kind: KeyKind.STANDARD, code: "KeyJ"},
        {symbol: "K", kind: KeyKind.STANDARD, code: "KeyK"},
        {symbol: "L", kind: KeyKind.STANDARD, code: "KeyL"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Semicolon"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Quote"},
        {symbol: "", kind: KeyKind.BIG, code: "Enter"},
    ],
    [
        {symbol: "", kind: KeyKind.HUGE, code: "ShiftLeft"},
        {symbol: "Z", kind: KeyKind.STANDARD, code: "KeyZ"},
        {symbol: "X", kind: KeyKind.STANDARD, code: "KeyX"},
        {symbol: "C", kind: KeyKind.STANDARD, code: "KeyC"},
        {symbol: "V", kind: KeyKind.STANDARD, code: "KeyV"},
        {symbol: "B", kind: KeyKind.STANDARD, code: "KeyB"},
        {symbol: "N", kind: KeyKind.STANDARD, code: "KeyN"},
        {symbol: "M", kind: KeyKind.STANDARD, code: "KeyM"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Comma"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Period"},
        {symbol: "", kind: KeyKind.STANDARD, code: "Slash"},
        {symbol: "", kind: KeyKind.HUGE, code: "ShiftRight"},
    ],
    [
        {symbol: "", kind: KeyKind.REGULAR, code: "ControlLeft"},
        {symbol: "", kind: KeyKind.REGULAR, code: "MetaLeft"},
        {symbol: "", kind: KeyKind.REGULAR, code: "AltLeft"},
        {symbol: "", kind: KeyKind.SPACE, code: "Space"},
        {symbol: "", kind: KeyKind.REGULAR, code: "AltRight"},
        {symbol: "", kind: KeyKind.REGULAR, code: "MetaRight"},
        {symbol: "", kind: KeyKind.REGULAR, code: "Menu"},
        {symbol: "", kind: KeyKind.REGULAR, code: "ControlRight"},
    ]
];

export type KeyConfigType = {
    symbol: string,
    kind: string,
    code: string
};