type Sentence {
    id: Int!
    text: String!
    ruby: String!
}

type SentenceIndicators {
    text: String!
    ruby: String!
    level: Int!
    difficulty: Float!
}

type Query {
    getApproxSentence(id: Int, level: Int!, difficulty: Float!): Sentence
}

query getApproxSentence($id: Int, $level: Int!, $difficulty: Float!) {
    getApproxSentence(id: $id, level: $level, difficulty: $difficulty) {
        id
        text
        ruby
    }
}
