type Sentence {
    text: String!
    ruby: String!
}

type SentenceIndicators {
    text: String!
    ruby: String!
    level: Int!
    difficulty: Float!
}

type Query {
    getApproxSentence(level: Int!, difficulty: Float!): SentenceIndicators
}

query getApproxSentence($level: Int!, $difficulty: Float!) {
    getApproxSentence(level: $level, difficulty: $difficulty) {
        text
        ruby
    }
}
