type Sentence {
  text: String!
  ruby: String!
  indicator: SentenceIndicators!
}

type SentenceIndicators {
  level: Int!
  difficulty: Int!
}

type Query {
  getApproxSentence(level: Int!, difficulty: Int!): Sentence
}

query getApproxSentence($level: Int!, $difficulty: Int!) {
  getApproxSentence(level: $level, difficulty: $difficulty) {
    text
    ruby
    indicator {
      level
      difficulty
    }
  }
}
